### ISSUE TITLE
[0.1.5] Wine Glasses and Mulled Wine Glasses do not give bottles back when drank

### ISSUE THREAD

**Issue by Gronglegrowth** [TheGridExpert/VampiresDelight#11] opened 2024-05-31 07:12 UTC
Wine Glasses, when consumed, don't give back a bottle as expected. Mulled Wine Glasses seem to *remove* glass bottles when consumed, instead of also giving a bottle back.

**Comment by TheGridExpert** [comment] 2024-05-31 07:38
Is this bug present in single player or server only? I tried to test it on my own server, but it worked as intended. In single player it works as well. The only place where I saw it so far is vampirism.co server.

**Comment by Gronglegrowth** [comment] 2024-05-31 08:01
I had noticed it in singleplayer. Maybe there's a mod conflict of some sort?

**Comment by TheGridExpert** [comment] 2024-05-31 08:02
I suppose so. I have no other ideas why it can be caused. Send mod list please

**Comment by Gronglegrowth** [comment] 2024-05-31 08:07
Here's a [modlist.md](https://github.com/user-attachments/files/15510374/modlist.md)
I'll see if I can find what might be doing it, as well.

**Comment by Gronglegrowth** [comment] 2024-05-31 08:32
I can't seem able to find it, oddly. I did notice that in an instance with only Vampire's Delight, Vampirism, and Farmer's Delight, stacks of either item will properly give bottles back unless it's the last item in the stack - that is, if you consume one from a stack of at least 2, it'll give you a bottle; but if the stack size is 1, it won't.

**Comment by TheGridExpert** [comment] 2024-05-31 08:56
Forgot to ask. Does it happen only with wine or orchid tea as well?

**Comment by Gronglegrowth** [comment] 2024-05-31 09:41
It does seem to also affect orchid tea.

**Comment by TheGridExpert** [comment] 2024-05-31 09:52
Does it work the same way with other vampire food like orchid ice cream and orchid cream soup?

**Comment by Gronglegrowth** [comment] 2024-05-31 10:02
Yes

**Comment by TheGridExpert** [comment] 2024-05-31 14:10
[VampiresDelight-0.1.5b-1.20.1.jar.zip](https://github.com/user-attachments/files/15514836/VampiresDelight-0.1.5b-1.20.1.jar.zip)
Try this version. It should be fixed here

**Comment by Gronglegrowth** [comment] 2024-06-01 02:53
Yes, fixed.

**Closed as completed** 2024-06-02 09:11 UTC
Labels: bug
