### ISSUE TITLE
New Update causes Exit code 1

### ISSUE THREAD

**Issue by Maxi90909** [TheGridExpert/VampiresDelight#15] opened 2024-06-27 13:18 UTC
Basically, I have mods that I removed from my modpack. Epic fight is one of them. For some reason when I use the newest version of your mod it causes exit code 1 crash due to it reusing epic fights and some other mods files, making it think they are in the mods folder despite being not there and not installed.

Lastest log -> https://cfpaste.modularity.gg/paste/?content=768367574001778729_1255859270000312351&filename=latest.log&raw=false

**Comment by TheGridExpert** [comment] 2024-06-27 18:53
Could you please provide a crush report if there's one? It would be more useful than latest log which doesn't show any connection between Vampire's Delight and Epic Fight issue. I think you better report it to Epic Fight mod

**Comment by Maxi90909** [comment] 2024-06-27 19:38
Sadly there is no crash report. It just shows exit code 1. The problem is I had epic fight at some point in my mods folder. I removed it without starting my world with it because it was crashing upon startup. For some reason your mod is reactivating the file I removed and therefore causing a crash. I have try and delete everything related to the mods epic fight and the other ones mentioned in the log. But I don't even have the mod active and it for some reason tryies to load the files of it when your mod is on version 0.1.6.

**Comment by TheGridExpert** [comment] 2024-06-27 20:23
Really weird. I looked through in details but Vampire's Delight is never mentioned in errors, the only thing about it is that it was loaded successfully. So, installing 0.1.5b version again helps it, right?

**Comment by Maxi90909** [comment] 2024-06-27 20:28
yes, installing the previos version helps. I will ask in the curse forge server now. For some reason Mods that I had at some point are trying to be read, this causes a crash as they are missing. I also have a weird issue where the mod ferrite core is being added back despite me removing it. Each time I update your mod it gets added back. I dunno why. I know vampire delight isn't being mentioned. But this crash only happens if the mod is on version 0.1.6. It doesn't occur on any other version. I tested this by updating it and as soon as I started the game after updating this crash occured.

**Comment by TheGridExpert** [comment] 2024-06-27 20:36
If it's added back then it means that VD depends on it and CF adds it, but it's not true. I can't come to any logical conclusion because there aren't many leads. You can try updating it and then remove ferrite core, but I suppose you have already done it, so maybe it didn't help

**Comment by Maxi90909** [comment] 2024-06-27 20:56
I am pin-pointing the issue by removing the mods the logs mention at the end. I think I found the issue.

**Comment by Maxi90909** [comment] 2024-06-27 21:11
![Screenshot (41)](https://github.com/TheGridExpert/VampiresDelight/assets/76815835/f82b2ad3-cebb-40f5-a9d2-9f4c72971c2e)
 So, I pinpointed the problem. The logs keept mentioning these mods. I haven't tested Kubejs and it's assosiateds yet. But Journeymap and enhanced celestials crash if you have eighter the one or the other or both.

**Comment by Maxi90909** [comment] 2024-06-27 21:13
Game also crashes with any of the Kubejs-Mods

**Comment by TheGridExpert** [comment] 2024-06-27 21:16
So, if you change the version of VD to 0.1.5b everything is fine, but updating it to 0.1.6 causes those mods to crush, right? Now it looks even weirder. I'm not sure if I can do anything, but I'll try researching what I can tomorrow. Thank you for the information

**Comment by Maxi90909** [comment] 2024-06-27 21:19
Yes Indeed. VD 0.1.5b works fine with them. But For some reason 0.1.6 causes it to crash with any of these mods in the picture.

**Comment by Maxi90909** [comment] 2024-06-27 21:31
[latest.log](https://github.com/user-attachments/files/16021487/latest.log)

One last thing, before I also go to sleep. This is the log without the mods in the picture. Maybe it helps. I litterally have like only 2 braincells to understand coding, so I barely understand any of it at all.

**Comment by ChiefArug** [comment] 2024-06-28 01:34
This is caused by your mixin plugin loading a whole hoard of Minecraft classes waaay too early by calling into a general utility class that loads those classes.

Specifically, nn the mixin plugin [VDMixinConfigPlugin.java#L28](https://github.com/TheGridExpert/VampiresDelight/blob/dev/src/main/java/net/grid/vampiresdelight/common/mixin/plugin/VDMixinConfigPlugin.java#L28) it loads the `VDIntegrationUtils` class when that lambda is called. When that class is first loaded it's <clinit> block loads, which includes setting the values of three ResourceLocation fields [VDIntegrationUtils.java#L72-L75](https://github.com/TheGridExpert/VampiresDelight/blob/dev/src/main/java/net/grid/vampiresdelight/common/utility/VDIntegrationUtils.java#L72-L75) which loads the ResourceLocation class. It also includes loading the Tier class and the Ingredient class which also loads the classes that those depend on. Not good.
Ideally the plugin would just have the 'is mod loaded' check directly in it and not get another messy util class to have the check.

**Comment by Maxi90909** [comment] 2024-06-28 04:59
Okay, how can I fix this? Is there any way to fix this?

**Comment by TsameCorvy** [comment] 2024-06-28 05:13
I'm getting the same issue right now lmfao
Just reverted the version back to 0.1.5.b and now the game loaded
I would send a crash log to help but I have the sinytra gang installed
Although I have another sinytraless modpack with this mod installed, let me test it

**Comment by TsameCorvy** [comment] 2024-06-28 05:19
Yeah, still crashing!
For now stick to 0.1.5b until 0.1.6 gets a patch, I suppose.
And there is indeed no crash log, I can only hand you a normal log.
[2024-06-27-2.log](https://github.com/user-attachments/files/16024506/2024-06-27-2.log)

**Comment by ChiefArug** [comment] 2024-06-28 05:35
There is no fix for the current version, @TheGridExpert needs to modify the code and publish a fixed release. For now downgrading to the previous version is the only way to continue using the mod.

**Comment by TheGridExpert** [comment] 2024-06-28 05:57
Yes, I know I need to modify it, I just have no idea at all what to modify as those logs show nothing

**Comment by TheGridExpert** [comment] 2024-06-28 06:04
ChiefArug, thank you for telling about Mixin plugin, I will fix it now and release a patch as soon as possible

**Comment by Maxi90909** [comment] 2024-06-28 06:13
Thanks for letting me know Chiefarug. I thought this is just a "Me-Problem" as I have many mods

**Comment by TheGridExpert** [comment] 2024-06-28 06:26
@Maxi90909 Could you please check if this version works? I implemented changed ChiefArug said, now it shouldn't crush
[VampiresDelight-0.1.6b-1.20.1.jar.zip](https://github.com/user-attachments/files/16025213/VampiresDelight-0.1.6b-1.20.1.jar.zip)

**Comment by Maxi90909** [comment] 2024-06-28 06:30
Will try, hold up

**Comment by Maxi90909** [comment] 2024-06-28 06:45
It loaded fine, without giving me exit code 1. I will try to load my world now and see if that also works.

**Comment by Maxi90909** [comment] 2024-06-28 08:45
It works fine. But I am getting a lot of lag. Also I can't grow orchid seeds in a botany pot as the cursed soil farmland item (needed to grow it) and any other farmland item is unobtainable in survival even when mined with silk touch.

**Comment by TheGridExpert** [comment] 2024-06-28 09:51
Can't say about lag, but in order to get cursed farmland you just need to plow it inside the pot. Just place cursed earth in pot and plow the pot

**Comment by Maxi90909** [comment] 2024-06-28 11:06
The lag is caused by my Computer. It was a bit too hot. But that is normal. The problem with the pot is the following. I can put the cursed dirt, cursed grass block in the pot. But I can't put the orchid seed in then. I have tested this by giving myself cursed farmland and putting it in the pot along with a orchid seed. Then the plant grows, BUT only then. The problem is basically: The orchid seed can only be grown on cursed_farmland. However you can't obtain that block in survival, even if you mine cursed farmland with silk_touch it only gives me cursed dirt, which I can put in the botany pot but the orchid seed doesn't accept it. This is proven by JEI saying that in order to grow orchid seeds in a botany pot it needs cursed "farmland" normal cursed dirt or grass doens't work. That is the issue.

**Comment by Maxi90909** [comment] 2024-06-28 11:13
![Screenshot (43)](https://github.com/TheGridExpert/VampiresDelight/assets/76815835/3f1d8ef0-10a5-4038-b822-16c3bdb36695)

This is the issue. Unlike the mushroom (The one added by your mod) The seeds only accept "Farmland" in the pot. However that is not obtainable. Easiest way to solve this is to add cursed dirt as an acceptable block for the orchid seed and/or making the cursed farmland craftable like mystical agriculture does. (Cafting recipe is just any hoe and normal dirt to make normal farmland) In the case of Vampire delight just any hoe and cursed dirt from vampirism.

**Comment by Maxi90909** [comment] 2024-06-28 11:16
Forget everything I just said. I just discovered you can use a hoe on a dirtlike block in a botany pot. Jezz I DIDN'T even know you could do that. I did not know this fearture existed.

**Comment by TheGridExpert** [comment] 2024-06-28 13:58
As the issue was fixed I'll close it.
ChiefArug, thank you for your help a lot!

**Closed as completed by TheGridExpert** 2024-06-28 13:58 UTC
Labels: crash, mod compatibility
